In [1]:
#importing libraries
import numpy as np
import pandas as pd

In [2]:
#reading the dataset
dataset = pd.read_csv(r"F:\Andrina\Externship\Code Files\bank.csv")

In [3]:
dataset.head(2)

age     job  marital  education default  balance housing loan  contact  \
0   59  admin.  married  secondary      no     2343     yes   no  unknown   
1   56  admin.  married  secondary      no       45      no   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes  
1    5   may      1467         1     -1         0  unknown     yes

In [4]:
#checking for null values
dataset.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

### the columns day, month and pdays do not affect the final output, thus removing those columns from x 

In [5]:
#splitting the data to  x and y 
#the columns day, month and pdays do not affect the final output, thus removing those columns from x 
m = dataset.iloc[:,0:9]
n = dataset.iloc[:,11:13]
o = dataset.iloc[:,14:16]

In [6]:
x = m.join(n)
x = x.join(o)

In [7]:
x = x.values
#y is the output data. It consists of the deposit column
y = dataset.iloc[:,16:].values

In [8]:
x[0]
# the current index values of the coulmns in x are as below
#  0- age
#  1- job
#  2- marital
#  3- education
#  4- default
#  5- balance
#  6- housing
#  7- loan
#  8- contact
#  9- duration
#  10- campaign
#  11- previous
#  12- poutcome
#  13- deposit

array([59, 'admin.', 'married', 'secondary', 'no', 2343, 'yes', 'no',
       'unknown', 1042, 1, 0, 'unknown'], dtype=object)

In [9]:
y

array([['yes'],
       ['yes'],
       ['yes'],
       ...,
       ['no'],
       ['no'],
       ['no']], dtype=object)

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [11]:
#the columns day, month and pdays do not affect the final output, thus removing those columns from x 
#while splitting data to x and y
ct = ColumnTransformer([("one",OneHotEncoder(),[1,2,3,4,6,7,8,12])],remainder ="passthrough")
x = ct.fit_transform(x)

In [12]:
ct1 = ColumnTransformer([("one",OneHotEncoder(),[0])],remainder ="passthrough")
y = ct1.fit_transform(y)

In [13]:
x[0]

array([1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0,
       0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 59, 2343, 1042, 1, 0], dtype=object)

In [33]:
y[70]

array([0., 1.])

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state=0)

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [17]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense 

In [18]:
categorical = Sequential()

In [19]:
x_train.shape

(8929, 37)

In [20]:
y_train.shape

(8929, 2)

In [21]:
categorical.add(Dense( units= 37, kernel_initializer= "random_uniform", activation="relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [22]:
categorical.add(Dense( units= 74, kernel_initializer= "random_uniform", activation="relu"))

In [23]:
categorical.add(Dense( units= 74, kernel_initializer= "random_uniform", activation="relu"))

In [24]:
categorical.add(Dense( units= 74, kernel_initializer= "random_uniform", activation="relu"))

In [25]:
categorical.add(Dense( units= 2, kernel_initializer= "random_uniform", activation="softmax"))

In [26]:
categorical.compile(optimizer = "rmsprop", loss = "categorical_crossentropy", metrics=["accuracy"]) 

In [29]:
categorical.fit(x_train, y_train, epochs = 350) 

Epoch 1/350
8929/8929 [==============================] - 1s 62us/sample - loss: 0.1104 - acc: 0.9721
Epoch 2/350
8929/8929 [==============================] - 1s 68us/sample - loss: 0.0823 - acc: 0.9718
Epoch 3/350
8929/8929 [==============================] - 1s 61us/sample - loss: 0.1008 - acc: 0.9692
Epoch 4/350
8929/8929 [==============================] - 1s 62us/sample - loss: 0.0900 - acc: 0.9701
Epoch 5/350
8929/8929 [==============================] - 1s 63us/sample - loss: 0.0901 - acc: 0.9736
Epoch 6/350
8929/8929 [==============================] - 1s 63us/sample - loss: 0.0849 - acc: 0.9735
Epoch 7/350
8929/8929 [==============================] - 1s 61us/sample - loss: 0.0909 - acc: 0.9716
Epoch 8/350
8929/8929 [==============================] - 1s 62us/sample - loss: 0.0779 - acc: 0.9749
Epoch 9/350
8929/8929 [==============================] - ETA: 0s - loss: 0.0802 - acc: 0.974 - 1s 62us/sample - loss: 0.0820 - acc: 0.9733
Epoch 10/350
8929/8929 [=============================

8929/8929 [==============================] - 1s 60us/sample - loss: 0.0930 - acc: 0.9754
Epoch 81/350
8929/8929 [==============================] - 1s 60us/sample - loss: 0.0817 - acc: 0.9751
Epoch 82/350
8929/8929 [==============================] - 1s 61us/sample - loss: 0.0836 - acc: 0.9777
Epoch 83/350
8929/8929 [==============================] - 1s 60us/sample - loss: 0.0800 - acc: 0.9767
Epoch 84/350
8929/8929 [==============================] - 1s 60us/sample - loss: 0.1101 - acc: 0.9738
Epoch 85/350
8929/8929 [==============================] - 1s 61us/sample - loss: 0.0793 - acc: 0.9775
Epoch 86/350
8929/8929 [==============================] - 1s 60us/sample - loss: 0.0856 - acc: 0.9746
Epoch 87/350
8929/8929 [==============================] - 1s 60us/sample - loss: 0.0838 - acc: 0.9765
Epoch 88/350
8929/8929 [==============================] - 1s 59us/sample - loss: 0.0916 - acc: 0.9772
Epoch 89/350
8929/8929 [==============================] - 1s 59us/sample - loss: 0.0878 - acc: 

8929/8929 [==============================] - 1s 66us/sample - loss: 0.0670 - acc: 0.9801
Epoch 160/350
8929/8929 [==============================] - 1s 61us/sample - loss: 0.0929 - acc: 0.9810
Epoch 161/350
8929/8929 [==============================] - 1s 62us/sample - loss: 0.0784 - acc: 0.9783
Epoch 162/350
8929/8929 [==============================] - 1s 65us/sample - loss: 0.0591 - acc: 0.9822
Epoch 163/350
8929/8929 [==============================] - 1s 61us/sample - loss: 0.0662 - acc: 0.9814
Epoch 164/350
8929/8929 [==============================] - 1s 61us/sample - loss: 0.0634 - acc: 0.9800
Epoch 165/350
8929/8929 [==============================] - 1s 60us/sample - loss: 0.0883 - acc: 0.9801
Epoch 166/350
8929/8929 [==============================] - 1s 61us/sample - loss: 0.0584 - acc: 0.9830
Epoch 167/350
8929/8929 [==============================] - 1s 60us/sample - loss: 0.0662 - acc: 0.9804
Epoch 168/350
8929/8929 [==============================] - 1s 61us/sample - loss: 0.071

8929/8929 [==============================] - 1s 61us/sample - loss: 0.0995 - acc: 0.9820
Epoch 239/350
8929/8929 [==============================] - 1s 59us/sample - loss: 0.0631 - acc: 0.9810
Epoch 240/350
8929/8929 [==============================] - 1s 61us/sample - loss: 0.0661 - acc: 0.9828
Epoch 241/350
8929/8929 [==============================] - 1s 59us/sample - loss: 0.0672 - acc: 0.9824
Epoch 242/350
8929/8929 [==============================] - 1s 59us/sample - loss: 0.0796 - acc: 0.9828
Epoch 243/350
8929/8929 [==============================] - 1s 60us/sample - loss: 0.0804 - acc: 0.9816
Epoch 244/350
8929/8929 [==============================] - 1s 60us/sample - loss: 0.0741 - acc: 0.9815
Epoch 245/350
8929/8929 [==============================] - 1s 59us/sample - loss: 0.0764 - acc: 0.9807
Epoch 246/350
8929/8929 [==============================] - 1s 61us/sample - loss: 0.1073 - acc: 0.9828
Epoch 247/350
8929/8929 [==============================] - 1s 61us/sample - loss: 0.081

8929/8929 [==============================] - 1s 59us/sample - loss: 0.0657 - acc: 0.9836
Epoch 317/350
8929/8929 [==============================] - 1s 59us/sample - loss: 0.0962 - acc: 0.9793
Epoch 318/350
8929/8929 [==============================] - 1s 59us/sample - loss: 0.0856 - acc: 0.9839
Epoch 319/350
8929/8929 [==============================] - 1s 59us/sample - loss: 0.0743 - acc: 0.9825
Epoch 320/350
8929/8929 [==============================] - 1s 61us/sample - loss: 0.0646 - acc: 0.9844
Epoch 321/350
8929/8929 [==============================] - 1s 60us/sample - loss: 0.0655 - acc: 0.9835
Epoch 322/350
8929/8929 [==============================] - 1s 60us/sample - loss: 0.0580 - acc: 0.9845
Epoch 323/350
8929/8929 [==============================] - 1s 60us/sample - loss: 0.0716 - acc: 0.9822
Epoch 324/350
8929/8929 [==============================] - 1s 60us/sample - loss: 0.0587 - acc: 0.9847
Epoch 325/350
8929/8929 [==============================] - 1s 60us/sample - loss: 0.061

In [34]:
ypred = categorical.predict(x_test)

In [36]:
ypred

array([[1.0000000e+00, 0.0000000e+00],
       [4.2341362e-09, 1.0000000e+00],
       [1.0000000e+00, 0.0000000e+00],
       ...,
       [8.8607122e-19, 1.0000000e+00],
       [1.0000000e+00, 0.0000000e+00],
       [1.1459228e-02, 9.8854083e-01]], dtype=float32)

In [39]:
ypred = ypred>0.5

In [42]:
deposit = ["No","Yes"]
yp = categorical.predict(sc.transform(ct.transform([[59, 'admin.', 'married', 'secondary', 'no', 2343, 'yes', 'no',
       'unknown', 1042, 1, 0, 'unknown']])))
prediction = deposit[np.argmax(yp)]
prediction

'Yes'

In [35]:
dataset.head(1)

age     job  marital  education default  balance housing loan  contact  \
0   59  admin.  married  secondary      no     2343     yes   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes