# This model predicts 4 types of precious stones: 
# Amethyst, Jade, Rose Quartz and Sapphire

### 1. Importing Libraries

In [1]:
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense, Convolution2D, Flatten,MaxPooling2D

In [2]:
from  tensorflow.keras.preprocessing.image import ImageDataGenerator 

### 2. Image preprocessing

creating 2 variables for augmentation techniques

In [3]:
train_datagen = ImageDataGenerator(rescale = 1./255, shear_range = 0.2, zoom_range = 0.2, horizontal_flip = True)
test_datagen = ImageDataGenerator(rescale = 1./255, shear_range = 0.2, zoom_range = 0.2, horizontal_flip = True)

load dataset and apply augmentation techniques to loaded dataset

In [4]:
x_train = train_datagen.flow_from_directory(r"F:\Andrina\Externship\Code Files\Precious-stone data\trainset", 
                                            target_size = (64,64),
                                           batch_size = 32,
                                            class_mode = "categorical")

x_test = test_datagen.flow_from_directory(r"F:\Andrina\Externship\Code Files\Precious-stone data\testset", 
                                            target_size = (64,64),
                                           batch_size = 32,
                                            class_mode = "categorical")

Found 456 images belonging to 4 classes.
Found 249 images belonging to 4 classes.


### 3. Train the model

In [5]:
cnn = Sequential()

##### add convolution layer

In [6]:
cnn.add(Convolution2D(32,(3,3),input_shape = (64,64,3)))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


##### add maxpooling layer

In [7]:
cnn.add(MaxPooling2D((2,2)))

##### add flatten layer

In [8]:
cnn.add(Flatten())

##### add hidden layer

In [9]:
cnn.add(Dense(units = 128 , kernel_initializer="random_uniform", activation = "relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


##### add output layer

In [10]:
cnn.add(Dense(units = 4 , kernel_initializer="random_uniform", activation = "softmax"))

##### configure learning

In [11]:
cnn.compile(optimizer = "rmsprop", loss = "categorical_crossentropy", metrics = ["accuracy"])

##### train model

In [12]:
cnn.fit_generator(x_train, steps_per_epoch = 456/32, epochs=15, validation_data = x_test, validation_steps = 249/32)

Epoch 1/15
15/14 [===============================] - 9s 582ms/step - loss: 2.1554 - acc: 0.5263 - val_loss: 0.6684 - val_acc: 0.7108
Epoch 2/15
15/14 [===============================] - 5s 306ms/step - loss: 0.4060 - acc: 0.8706 - val_loss: 0.1645 - val_acc: 0.9719
Epoch 3/15
15/14 [===============================] - 5s 304ms/step - loss: 0.2316 - acc: 0.9320 - val_loss: 0.0893 - val_acc: 0.9920
Epoch 4/15
15/14 [===============================] - 5s 329ms/step - loss: 0.0903 - acc: 0.9781 - val_loss: 0.0597 - val_acc: 0.9920
Epoch 5/15
15/14 [===============================] - 5s 301ms/step - loss: 0.1049 - acc: 0.9627 - val_loss: 0.0441 - val_acc: 0.9960
Epoch 6/15
15/14 [===============================] - 4s 279ms/step - loss: 0.0566 - acc: 0.9825 - val_loss: 0.1620 - val_acc: 0.9558
Epoch 7/15
15/14 [===============================] - 5s 344ms/step - loss: 0.0415 - acc: 0.9912 - val_loss: 0.0360 - val_acc: 0.9960
Epoch 8/15
15/14 [===============================] - 4s 294ms/step - 

##### save model

In [13]:
cnn.save("prestone.h5")

### 4. Test the model 

In [14]:
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image

##### load saved model

In [15]:
model = load_model("prestone.h5")

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


#### Prediction Index
##### 1000 amethyst
##### 0100 jade
##### 0010 rosequartz
##### 0001 sapphire

## Test for Rose quartz 

In [28]:
img = image.load_img("rosequartz.jpg",target_size = (64,64))
x = image.img_to_array(img)
x = np.expand_dims(x,axis =0)
pred = model.predict(x)
print(pred)
prediction = index[np.argmax(pred[0])]
prediction

[[0. 0. 1. 0.]]


'rose quartz'

## Test for Sapphire

In [24]:
img = image.load_img("sapphire.jpg",target_size = (64,64))
x = image.img_to_array(img)
x = np.expand_dims(x,axis =0)
pred = model.predict(x)
print(pred)
prediction = index[np.argmax(pred[0])]
prediction

[[0. 0. 0. 1.]]


'sapphire'

## Test for Jade 

In [25]:
img = image.load_img("jade.jpg",target_size = (64,64))
x = image.img_to_array(img)
x = np.expand_dims(x,axis =0)
pred = model.predict(x)
print(pred)
prediction = index[np.argmax(pred[0])]
prediction

[[0. 1. 0. 0.]]


'jade'

## Test for Amethyst

In [27]:
img = image.load_img("amethyst.jpg",target_size = (64,64))
x = image.img_to_array(img)
x = np.expand_dims(x,axis =0)
pred = model.predict(x)
print(pred)
prediction = index[np.argmax(pred[0])]
prediction

[[1. 0. 0. 0.]]


'amethyst'