In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv(r"F:\Andrina\Externship\Code Files\bank.csv")

In [3]:
dataset.head(2)

age     job  marital  education default  balance housing loan  contact  \
0   59  admin.  married  secondary      no     2343     yes   no  unknown   
1   56  admin.  married  secondary      no       45      no   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes  
1    5   may      1467         1     -1         0  unknown     yes

In [4]:
dataset.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

In [5]:
m = dataset.iloc[:,0:9]
n = dataset.iloc[:,11:13]
o = dataset.iloc[:,14:16]

In [6]:
x = m.join(n)
x = x.join(o)

In [7]:
x = x.values
y = dataset.iloc[:,16:].values

In [8]:
x

array([[59, 'admin.', 'married', ..., 1, 0, 'unknown'],
       [56, 'admin.', 'married', ..., 1, 0, 'unknown'],
       [41, 'technician', 'married', ..., 1, 0, 'unknown'],
       ...,
       [32, 'technician', 'single', ..., 2, 0, 'unknown'],
       [43, 'technician', 'married', ..., 2, 5, 'failure'],
       [34, 'technician', 'married', ..., 1, 0, 'unknown']], dtype=object)

In [9]:
y

array([['yes'],
       ['yes'],
       ['yes'],
       ...,
       ['no'],
       ['no'],
       ['no']], dtype=object)

In [10]:
y = np.where(y=='yes',1,y)
y = np.where(y=='no',0,y)

In [11]:
y

array([[1],
       [1],
       [1],
       ...,
       [0],
       [0],
       [0]], dtype=object)

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [13]:
ct = ColumnTransformer([("one",OneHotEncoder(),[1,2,3,4,6,7,8,12])],remainder ="passthrough")
x = ct.fit_transform(x)

In [14]:
x[0]

array([1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0,
       0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 59, 2343, 1042, 1, 0], dtype=object)

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state=0)

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [17]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense 

In [18]:
classification = Sequential()

In [19]:
x_train.shape

(8929, 37)

In [20]:
classification.add(Dense( units= 37, kernel_initializer= "random_uniform", activation="relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [21]:
classification.add(Dense( units= 74, kernel_initializer= "random_uniform", activation="relu"))

In [22]:
classification.add(Dense( units= 74, kernel_initializer= "random_uniform", activation="relu"))

In [23]:
classification.add(Dense( units= 1, kernel_initializer= "random_uniform", activation="sigmoid"))

In [24]:
classification.compile(optimizer = "adam", loss = "binary_crossentropy", metrics=["accuracy"]) 

In [27]:
classification.fit(x_train, y_train, epochs = 100) 

Epoch 1/100
8929/8929 [==============================] - 1s 73us/sample - loss: 0.2433 - acc: 0.8908
Epoch 2/100
8929/8929 [==============================] - 1s 74us/sample - loss: 0.2446 - acc: 0.8882
Epoch 3/100
8929/8929 [==============================] - 1s 71us/sample - loss: 0.2467 - acc: 0.8878
Epoch 4/100
8929/8929 [==============================] - 1s 71us/sample - loss: 0.2466 - acc: 0.8880
Epoch 5/100
8929/8929 [==============================] - 1s 75us/sample - loss: 0.2372 - acc: 0.8915
Epoch 6/100
8929/8929 [==============================] - 1s 71us/sample - loss: 0.2363 - acc: 0.8933
Epoch 7/100
8929/8929 [==============================] - 1s 71us/sample - loss: 0.2339 - acc: 0.8910
Epoch 8/100
8929/8929 [==============================] - 1s 75us/sample - loss: 0.2322 - acc: 0.8951
Epoch 9/100
8929/8929 [==============================] - 1s 73us/sample - loss: 0.2309 - acc: 0.8958
Epoch 10/100
8929/8929 [==============================] - 1s 74us/sample - loss: 0.2321 - a

8929/8929 [==============================] - 1s 72us/sample - loss: 0.1204 - acc: 0.9494
Epoch 81/100
8929/8929 [==============================] - 1s 73us/sample - loss: 0.1389 - acc: 0.9423
Epoch 82/100
8929/8929 [==============================] - 1s 74us/sample - loss: 0.1278 - acc: 0.9467
Epoch 83/100
8929/8929 [==============================] - 1s 75us/sample - loss: 0.1365 - acc: 0.9424
Epoch 84/100
8929/8929 [==============================] - 1s 71us/sample - loss: 0.1191 - acc: 0.9498
Epoch 85/100
8929/8929 [==============================] - 1s 74us/sample - loss: 0.1198 - acc: 0.9479
Epoch 86/100
8929/8929 [==============================] - 1s 76us/sample - loss: 0.1577 - acc: 0.9347
Epoch 87/100
8929/8929 [==============================] - 1s 81us/sample - loss: 0.1574 - acc: 0.9382
Epoch 88/100
8929/8929 [==============================] - 1s 77us/sample - loss: 0.1407 - acc: 0.9429
Epoch 89/100
8929/8929 [==============================] - 1s 77us/sample - loss: 0.1330 - acc: 

In [28]:
ypred = classification.predict(x_test)

In [29]:
ypred

array([[0.0000000e+00],
       [1.0000000e+00],
       [2.3841858e-07],
       ...,
       [9.9999285e-01],
       [2.3761392e-04],
       [9.9494284e-01]], dtype=float32)

In [30]:
y_test

array([[0],
       [1],
       [0],
       ...,
       [1],
       [1],
       [0]], dtype=object)

In [31]:
ypred = ypred>0.5

In [32]:
ypred

array([[False],
       [ True],
       [False],
       ...,
       [ True],
       [False],
       [ True]])

In [35]:
dataset.head(1)

age     job  marital  education default  balance housing loan  contact  \
0   59  admin.  married  secondary      no     2343     yes   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes

In [36]:
yp = classification.predict(sc.transform(ct.transform([[59, 'admin.', 'married', 'secondary', 'no', 2343, 'yes', 'no',
       'unknown', 1042, 1, 0, 'unknown']])))

In [37]:
yp > 0.5
if(yp>0.5):
    print("Yes")
else:
    print("No")

Yes


In [40]:
yp = classification.predict(sc.transform(ct.transform([[38, 'management', 'married', 'tertiary', 'no', 5432, 'yes', 'yes',
       'cellular', 707, 1, 2, 'failure']])))

In [41]:
yp > 0.5
if(yp>0.5):
    print("Yes")
else:
    print("No")

No
