In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv(r"F:\Andrina\Externship\Code Files\bank.csv")

In [3]:
dataset.head(5)

age         job  marital  education default  balance housing loan  contact  \
0   59      admin.  married  secondary      no     2343     yes   no  unknown   
1   56      admin.  married  secondary      no       45      no   no  unknown   
2   41  technician  married  secondary      no     1270     yes   no  unknown   
3   55    services  married  secondary      no     2476     yes   no  unknown   
4   54      admin.  married   tertiary      no      184      no   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes  
1    5   may      1467         1     -1         0  unknown     yes  
2    5   may      1389         1     -1         0  unknown     yes  
3    5   may       579         1     -1         0  unknown     yes  
4    5   may       673         2     -1         0  unknown     yes

In [4]:
dataset.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

In [9]:
m = dataset.iloc[:,0:9]
n = dataset.iloc[:,11:13]
o = dataset.iloc[:,14:16]


In [11]:
x = m.join(n)
x = x.join(o)


In [13]:
x = x.values
y = dataset.iloc[:,16:].values

In [14]:
x

array([[59, 'admin.', 'married', ..., 1, 0, 'unknown'],
       [56, 'admin.', 'married', ..., 1, 0, 'unknown'],
       [41, 'technician', 'married', ..., 1, 0, 'unknown'],
       ...,
       [32, 'technician', 'single', ..., 2, 0, 'unknown'],
       [43, 'technician', 'married', ..., 2, 5, 'failure'],
       [34, 'technician', 'married', ..., 1, 0, 'unknown']], dtype=object)

In [28]:
y

array([['yes'],
       ['yes'],
       ['yes'],
       ...,
       ['no'],
       ['no'],
       ['no']], dtype=object)

In [16]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [17]:
ct = ColumnTransformer([("one",OneHotEncoder(),[1,2,3,4,6,7,8,12])],remainder ="passthrough")
x = ct.fit_transform(x)

In [18]:
x[0]

array([1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0,
       0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 59, 2343, 1042, 1, 0], dtype=object)

In [19]:
x.shape

(11162, 37)

In [20]:
ct1 = ColumnTransformer([("one",OneHotEncoder(),[0])],remainder ="passthrough")
y = ct1.fit_transform(y)

In [21]:
y[0]

array([0., 1.])

In [22]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state=0)

In [23]:
print(x.shape,"XShape")
print(y.shape,"YShape")
print(x_train.shape,"Xtrain")
print(y_train.shape,"Ytrain")
print(x_test.shape,"Xtest")
print(y_test.shape,"Ytest")

(11162, 37) XShape
(11162, 2) YShape
(8929, 37) Xtrain
(8929, 2) Ytrain
(2233, 37) Xtest
(2233, 2) Ytest


In [24]:
x_train[0:2,:]

array([[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0,
        0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 49, 104, 285, 1, 0],
       [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0,
        0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 59, 514, 261, 1, 0]], dtype=object)

In [25]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [26]:
x_train[0:2,:]

array([[-0.37172192, -0.45760242, -0.17658264, -0.1589378 ,  1.8452729 ,
        -0.27363591, -0.1931085 , -0.30435733, -0.17992689, -0.44212513,
        -0.18025832, -0.08293772, -0.36485864,  0.86351031, -0.66975544,
        -0.39346051,  1.01614555, -0.69993206, -0.21741017,  0.12621015,
        -0.12621015, -1.05825117,  1.05825117,  0.39003722, -0.39003722,
        -1.60273048, -0.27292594,  1.93439945, -0.35031555, -0.22657536,
        -0.32939951,  0.58661881,  0.64941897, -0.44565283, -0.2483547 ,
        -0.56394809, -0.35888264],
       [-0.37172192, -0.45760242, -0.17658264, -0.1589378 , -0.54192526,
         3.65449114, -0.1931085 , -0.30435733, -0.17992689, -0.44212513,
        -0.18025832, -0.08293772,  2.7407875 , -1.15806377, -0.66975544,
        -0.39346051,  1.01614555, -0.69993206, -0.21741017,  0.12621015,
        -0.12621015,  0.94495525, -0.94495525,  0.39003722, -0.39003722,
         0.62393522, -0.27292594, -0.51695631, -0.35031555, -0.22657536,
        -0.32939