In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv(r"F:\Andrina\Externship\Code Files\50_Startups.csv")

In [3]:
dataset

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87              NaN  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08             NaN        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [4]:
dataset.isnull().any()

R&D Spend          False
Administration      True
Marketing Spend     True
State              False
Profit             False
dtype: bool

In [5]:
dataset.isnull().sum()

R&D Spend          0
Administration     1
Marketing Spend    1
State              0
Profit             0
dtype: int64

In [6]:
dataset["Administration"].fillna(dataset["Administration"].mean(),inplace=True)
dataset["Marketing Spend"].fillna(dataset["Marketing Spend"].mean(),inplace=True)

In [7]:
dataset.isnull().any()

R&D Spend          False
Administration     False
Marketing Spend    False
State              False
Profit             False
dtype: bool

In [8]:
dataset.iloc[:,0:4]

R&D Spend  Administration  Marketing Spend       State
0   165349.20   136897.800000    471784.100000    New York
1   162597.70   151377.590000    443898.530000  California
2   153441.51   101145.550000    407934.540000     Florida
3   144372.41   118671.850000    383199.620000    New York
4   142107.34    91391.770000    366168.420000     Florida
5   131876.90    99814.710000    362861.360000    New York
6   134615.46   147198.870000    212725.266735  California
7   130298.13   145530.060000    323876.680000     Florida
8   120542.52   148718.950000    311613.290000    New York
9   123334.88   108679.170000    304981.620000  California
10  101913.08   121564.038163    229160.950000     Florida
11  100671.96    91790.610000    249744.550000  California
12   93863.75   127320.380000    249839.440000     Florida
13   91992.39   135495.070000    252664.930000  California
14  119943.24   156547.420000    256512.920000     Florida
15  114523.61   122616.840000    261776.230000    New York
16   78013.11   121597.550000    264346.060000  California
17   94657.16   145077.580000    282574.310000    New York
18   91749.16   114175.790000    294919.570000     Florida
19   86419.70   153514.110000         0.000000    New York
20   76253.86   113867.300000    298664.470000  California
21   78389.47   153773.430000    299737.290000    New York
22   73994.56   122782.750000    303319.260000     Florida
23   67532.53   105751.030000    304768.730000     Florida
24   77044.01    99281.340000    140574.810000    New York
25   64664.71   139553.160000    137962.620000  California
26   75328.87   144135.980000    134050.070000     Florida
27   72107.60   127864.550000    353183.810000    New York
28   66051.52   182645.560000    118148.200000     Florida
29   65605.48   153032.060000    107138.380000    New York
30   61994.48   115641.280000     91131.240000     Florida
31   61136.38   152701.920000     88218.230000    New York
32   63408.86   129219.610000     46085.250000  California
33   55493.95   103057.490000    214634.810000     Florida
34   46426.07   157693.920000    210797.670000  California
35   46014.02    85047.440000    205517.640000    New York
36   28663.76   127056.210000    201126.820000     Florida
37   44069.95    51283.140000    197029.420000  California
38   20229.59    65947.930000    185265.100000    New York
39   38558.51    82982.090000    174999.300000  California
40   28754.33   118546.050000    172795.670000  California
41   27892.92    84710.770000    164470.710000     Florida
42   23640.93    96189.630000    148001.110000  California
43   15505.73   127382.300000     35534.170000    New York
44   22177.74   154806.140000     28334.720000  California
45    1000.23   124153.040000      1903.930000    New York
46    1315.46   115816.210000    297114.460000     Florida
47       0.00   135426.920000         0.000000  California
48     542.05    51743.150000         0.000000    New York
49       0.00   116983.800000     45173.060000  California

In [9]:
x = dataset.iloc[:,0:4].values
y = dataset.iloc[:,4:5].values

In [10]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [11]:
x

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 212725.26673469393, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 121564.03816326526, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16

In [12]:
ct = ColumnTransformer([("one",OneHotEncoder(),[3])],remainder ="passthrough")
x = ct.fit_transform(x)

In [13]:
x.shape

(50, 6)

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size= 0.2,random_state=0)

In [15]:
x_train.shape

(40, 6)

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [17]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense 

In [18]:
regression = Sequential()

In [19]:
regression.add(Dense(units=6, kernel_initializer = "random_uniform", activation="relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [20]:
regression.add(Dense(units=12, kernel_initializer = "random_uniform", activation="relu"))

In [21]:
regression.add(Dense(units=12, kernel_initializer = "random_uniform", activation="relu"))

In [22]:
regression.add(Dense(units=12, kernel_initializer = "random_uniform", activation="relu"))

In [23]:
regression.add(Dense(units=12, kernel_initializer = "random_uniform", activation="relu"))

In [24]:
regression.add(Dense(units=1, kernel_initializer = "random_uniform", activation="relu"))

In [25]:
regression.compile(optimizer="rmsprop", loss="mse" ,metrics=["accuracy"])

In [29]:
regression.fit(x_train, y_train, epochs = 500) 

Epoch 1/500
40/40 [==============================] - 0s 200us/sample - loss: 8441493094.4000 - acc: 0.0000e+00
Epoch 2/500
40/40 [==============================] - 0s 0s/sample - loss: 8381802905.6000 - acc: 0.0000e+00
Epoch 3/500
40/40 [==============================] - 0s 400us/sample - loss: 8334114201.6000 - acc: 0.0000e+00
Epoch 4/500
40/40 [==============================] - 0s 200us/sample - loss: 8290715852.8000 - acc: 0.0000e+00
Epoch 5/500
40/40 [==============================] - 0s 200us/sample - loss: 8249586688.0000 - acc: 0.0000e+00
Epoch 6/500
40/40 [==============================] - 0s 200us/sample - loss: 8203631923.2000 - acc: 0.0000e+00
Epoch 7/500
40/40 [==============================] - 0s 200us/sample - loss: 8153494528.0000 - acc: 0.0000e+00
Epoch 8/500
40/40 [==============================] - 0s 200us/sample - loss: 8109888307.2000 - acc: 0.0000e+00
Epoch 9/500
40/40 [==============================] - 0s 200us/sample - loss: 8061232947.2000 - acc: 0.0000e+00
Epoc

40/40 [==============================] - 0s 400us/sample - loss: 4844496691.2000 - acc: 0.0000e+00
Epoch 74/500
40/40 [==============================] - 0s 400us/sample - loss: 4793413427.2000 - acc: 0.0000e+00
Epoch 75/500
40/40 [==============================] - 0s 400us/sample - loss: 4747742310.4000 - acc: 0.0000e+00
Epoch 76/500
40/40 [==============================] - 0s 200us/sample - loss: 4705392947.2000 - acc: 0.0000e+00
Epoch 77/500
40/40 [==============================] - 0s 200us/sample - loss: 4659111936.0000 - acc: 0.0000e+00
Epoch 78/500
40/40 [==============================] - 0s 200us/sample - loss: 4603618969.6000 - acc: 0.0000e+00
Epoch 79/500
40/40 [==============================] - 0s 200us/sample - loss: 4551648768.0000 - acc: 0.0000e+00
Epoch 80/500
40/40 [==============================] - 0s 200us/sample - loss: 4501165875.2000 - acc: 0.0000e+00
Epoch 81/500
40/40 [==============================] - 0s 200us/sample - loss: 4448705740.8000 - acc: 0.0000e+00
Epoch

40/40 [==============================] - 0s 200us/sample - loss: 2674448947.2000 - acc: 0.0000e+00
Epoch 146/500
40/40 [==============================] - 0s 400us/sample - loss: 2663435059.2000 - acc: 0.0000e+00
Epoch 147/500
40/40 [==============================] - 0s 200us/sample - loss: 2648514150.4000 - acc: 0.0000e+00
Epoch 148/500
40/40 [==============================] - 0s 200us/sample - loss: 2640564838.4000 - acc: 0.0000e+00
Epoch 149/500
40/40 [==============================] - 0s 200us/sample - loss: 2630397184.0000 - acc: 0.0000e+00
Epoch 150/500
40/40 [==============================] - 0s 200us/sample - loss: 2622006630.4000 - acc: 0.0000e+00
Epoch 151/500
40/40 [==============================] - 0s 200us/sample - loss: 2613155225.6000 - acc: 0.0000e+00
Epoch 152/500
40/40 [==============================] - 0s 200us/sample - loss: 2603500979.2000 - acc: 0.0000e+00
Epoch 153/500
40/40 [==============================] - ETA: 0s - loss: 2502467584.0000 - acc: 0.0000e+ - 0s 0s

40/40 [==============================] - 0s 400us/sample - loss: 1998903756.8000 - acc: 0.0000e+00
Epoch 218/500
40/40 [==============================] - 0s 400us/sample - loss: 1990236416.0000 - acc: 0.0000e+00
Epoch 219/500
40/40 [==============================] - 0s 400us/sample - loss: 1980622438.4000 - acc: 0.0000e+00
Epoch 220/500
40/40 [==============================] - 0s 200us/sample - loss: 1972066713.6000 - acc: 0.0000e+00
Epoch 221/500
40/40 [==============================] - 0s 400us/sample - loss: 1962701747.2000 - acc: 0.0000e+00
Epoch 222/500
40/40 [==============================] - 0s 200us/sample - loss: 1955204864.0000 - acc: 0.0000e+00
Epoch 223/500
40/40 [==============================] - 0s 200us/sample - loss: 1945738956.8000 - acc: 0.0000e+00
Epoch 224/500
40/40 [==============================] - 0s 400us/sample - loss: 1934898790.4000 - acc: 0.0000e+00
Epoch 225/500
40/40 [==============================] - 0s 600us/sample - loss: 1926834662.4000 - acc: 0.0000e+

40/40 [==============================] - 0s 200us/sample - loss: 1363934976.0000 - acc: 0.0000e+00
Epoch 290/500
40/40 [==============================] - 0s 200us/sample - loss: 1356562073.6000 - acc: 0.0000e+00
Epoch 291/500
40/40 [==============================] - 0s 200us/sample - loss: 1348630246.4000 - acc: 0.0000e+00
Epoch 292/500
40/40 [==============================] - 0s 200us/sample - loss: 1340590873.6000 - acc: 0.0000e+00
Epoch 293/500
40/40 [==============================] - 0s 200us/sample - loss: 1332975897.6000 - acc: 0.0000e+00
Epoch 294/500
40/40 [==============================] - 0s 200us/sample - loss: 1324326656.0000 - acc: 0.0000e+00
Epoch 295/500
40/40 [==============================] - 0s 200us/sample - loss: 1316103065.6000 - acc: 0.0000e+00
Epoch 296/500
40/40 [==============================] - 0s 400us/sample - loss: 1305435852.8000 - acc: 0.0000e+00
Epoch 297/500
40/40 [==============================] - 0s 200us/sample - loss: 1295480320.0000 - acc: 0.0000e+

40/40 [==============================] - 0s 200us/sample - loss: 811703283.2000 - acc: 0.0000e+00
Epoch 362/500
40/40 [==============================] - 0s 200us/sample - loss: 805193248.0000 - acc: 0.0000e+00
Epoch 363/500
40/40 [==============================] - 0s 200us/sample - loss: 799701132.8000 - acc: 0.0000e+00
Epoch 364/500
40/40 [==============================] - 0s 200us/sample - loss: 791007884.8000 - acc: 0.0000e+00
Epoch 365/500
40/40 [==============================] - 0s 400us/sample - loss: 785918771.2000 - acc: 0.0000e+00
Epoch 366/500
40/40 [==============================] - 0s 200us/sample - loss: 777975321.6000 - acc: 0.0000e+00
Epoch 367/500
40/40 [==============================] - 0s 200us/sample - loss: 771559436.8000 - acc: 0.0000e+00
Epoch 368/500
40/40 [==============================] - 0s 200us/sample - loss: 765194675.2000 - acc: 0.0000e+00
Epoch 369/500
40/40 [==============================] - 0s 200us/sample - loss: 758575155.2000 - acc: 0.0000e+00
Epoch 

40/40 [==============================] - 0s 200us/sample - loss: 400580579.2000 - acc: 0.0000e+00
Epoch 435/500
40/40 [==============================] - 0s 200us/sample - loss: 397078966.4000 - acc: 0.0000e+00
Epoch 436/500
40/40 [==============================] - ETA: 0s - loss: 393516800.0000 - acc: 0.0000e+0 - 0s 200us/sample - loss: 393491372.8000 - acc: 0.0000e+00
Epoch 437/500
40/40 [==============================] - 0s 200us/sample - loss: 387687308.8000 - acc: 0.0000e+00
Epoch 438/500
40/40 [==============================] - 0s 0s/sample - loss: 382785126.4000 - acc: 0.0000e+00
Epoch 439/500
40/40 [==============================] - 0s 200us/sample - loss: 378633267.2000 - acc: 0.0000e+00
Epoch 440/500
40/40 [==============================] - 0s 200us/sample - loss: 374769561.6000 - acc: 0.0000e+00
Epoch 441/500
40/40 [==============================] - 0s 0s/sample - loss: 372711635.2000 - acc: 0.0000e+00
Epoch 442/500
40/40 [==============================] - 0s 200us/sample - l

In [30]:
ypred = regression.predict(x_test)

In [31]:
ypred

array([[119545.02 ],
       [107364.164],
       [120099.734],
       [ 54638.742],
       [160861.05 ],
       [126080.234],
       [ 58152.027],
       [ 97873.2  ],
       [117464.18 ],
       [143679.52 ]], dtype=float32)

In [32]:
y_test

array([[103282.38],
       [144259.4 ],
       [146121.95],
       [ 77798.83],
       [191050.39],
       [105008.31],
       [ 81229.06],
       [ 97483.56],
       [110352.25],
       [166187.94]])

In [35]:
yp = regression.predict(sc.transform(ct.transform([[120542.52,148718.950000,311613.290000,'New York']])))

In [36]:
yp

array([[161353.28]], dtype=float32)

In [37]:
y_test[8]

array([110352.25])